### ISSUE TITLE
is the apt repo down for https://apt.monax.io? #1408

### ISSUE THREAD

**Issue by V-ess** [monax/monax#1418] opened 2017-05-31 03:38 UTC
Please include in your bug report:

- [ ] `docker version`
- [ ] `monax version`
- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ ] operating system details (osx/windows/linux)
- [ Thanks for your help with issue #1408] what you expected to happen
- [ Please see https://monax.io/docs/tutorials/getting-started/?utm_campaign=aws_listing&utm_source=aws which is the website (still active) that is referencing eris instead of monax and old monax repo] what actually happened
- [ users like me coming from aws / eris platform are being routed to that old site] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by zramsay** [comment] 2017-06-01 16:16
thanks for reporting this issue. The cause was identified and will be fixed on our site shortly

**Closed by zramsay** 2017-06-01 16:16 UTC
